#!/bin/bash

set -ex
BASEDIR=/hugetmp/parr/ckdmip/mmm
INPREFIX=$BASEDIR/lw_raw/lblrtm-od
PROFFILE=$BASEDIR/conc/ckdmip_mmm_concentrations.nc
STARTCOL=1
ENDCOL=3
OUTDIR=$BASEDIR/lw_spectra
LBLRTM2NC=../../bin/lblrtm2nc
NBLOCK=4
OUTPREFIX=$OUTDIR/ckdmip_mmm_lw_spectra_

# $LBLRTM2NC $PROFFILE $INPREFIX cfc11 present-equivalent $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}cfc11_present-equivalent.h5
# $LBLRTM2NC $PROFFILE $INPREFIX cfc12 present $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}cfc12_present.h5
# $LBLRTM2NC $PROFFILE $INPREFIX co2 present $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}co2_present.h5
# $LBLRTM2NC $PROFFILE $INPREFIX n2o present $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}n2o_present.h5
# $LBLRTM2NC $PROFFILE $INPREFIX ch4 present $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}ch4_present.h5
# $LBLRTM2NC $PROFFILE $INPREFIX n2 constant $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}n2_constant.h5
# $LBLRTM2NC $PROFFILE $INPREFIX o2 constant $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}o2_constant.h5
# $LBLRTM2NC $PROFFILE $INPREFIX h2o median $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}h2o_median.h5
# $LBLRTM2NC $PROFFILE $INPREFIX h2o minimum $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}h2o_minimum.h5
# $LBLRTM2NC $PROFFILE $INPREFIX h2o maximum $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}h2o_maximum.h5
# $LBLRTM2NC $PROFFILE $INPREFIX o3 median $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}o3_median.h5
# $LBLRTM2NC $PROFFILE $INPREFIX o3 minimum $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}o3_minimum.h5
# $LBLRTM2NC $PROFFILE $INPREFIX o3 maximum $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}o3_maximum.h5

$LBLRTM2NC $PROFFILE $INPREFIX h2o-no-continuum median $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}h2o-no-continuum_median.h5
$LBLRTM2NC $PROFFILE $INPREFIX h2o-no-continuum minimum $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}h2o-no-continuum_minimum.h5
$LBLRTM2NC $PROFFILE $INPREFIX h2o-no-continuum maximum $STARTCOL $ENDCOL $NBLOCK ${OUTPREFIX}h2o-no-continuum_maximum.h5
